const assert=require('node:assert/strict'),loader=require('./load-model.cjs');
const {createRoom,departAdventure,advanceRoom}=loader.load('../lib/fairyRoomModel.ts');
const {tradeRoom}=loader.load('../lib/shopModel.ts');
const {PRODUCTS,BUYBACK}=loader.load('../lib/shopCatalog.ts');loader.restore();
const now=Date.parse('2026-09-16T00:00:00Z');let serial=0;
const trade=(r,a)=>tradeRoom(r,{...a,requestId:`test-${serial++}`},now);
const initial=createRoom(now),trip=departAdventure(initial,now,'forest',.5),returned=advanceRoom(trip,now+86400000);
assert.ok(returned.materials['forest-herb']>0);
assert.deepEqual(advanceRoom(returned,now+86400000).materials,returned.materials,'return cannot duplicate material reward');
assert.deepEqual(initial.materials,{});
assert.throws(()=>trade(initial,{type:'buy',shop:'elf',productId:'elf-potion'}));
const quantity=returned.materials['forest-herb'];let state=trade(returned,{type:'sell',shop:'elf',materialId:'forest-herb',quantity});
assert.equal(state.coins,quantity*5);assert.equal(state.materials['forest-herb'],0);
assert.throws(()=>trade(state,{type:'sell',shop:'elf',materialId:'forest-herb',quantity:1}));
assert.throws(()=>trade(returned,{type:'sell',shop:'elf',materialId:'forest-herb',quantity:-1}));
assert.throws(()=>trade(returned,{type:'sell',shop:'elf',materialId:'forest-herb',quantity:1.5}));
assert.throws(()=>trade(returned,{type:'sell',shop:'elf',materialId:'fairy-fiber',quantity:1}));
const sale={type:'sell',shop:'dwarf',materialId:'moon-stone',quantity:1,requestId:'same-sale'};
const sold=tradeRoom(returned,sale,now);assert.deepEqual(tradeRoom(sold,sale,now),sold);
state=trade({...state,health:50},{type:'buy',shop:'elf',productId:'elf-potion'});
assert.equal(state.coins,quantity*5-10);assert.equal(state.inventory['elf-potion'],1);
state=trade(state,{type:'use',productId:'elf-potion'});assert.equal(state.health,70);assert.equal(state.inventory['elf-potion'],0);
assert.throws(()=>trade(state,{type:'use',productId:'elf-potion'}));
let geared=trade({...initial,coins:100},{type:'buy',shop:'dwarf',productId:'dwarf-bag'});
const repeat=trade(geared,{type:'buy',shop:'dwarf',productId:'dwarf-bag'});assert.equal(repeat.coins,80);
geared=trade(geared,{type:'equip',productId:'dwarf-bag'});const boosted=departAdventure(geared,now,'forest',.5);
for(const [id,count] of Object.entries(trip.adventure.materials))assert.equal(boosted.adventure.materials[id],count+1);
geared=trade(geared,{type:'buy',shop:'dwarf',productId:'dwarf-sword'});geared=trade(geared,{type:'equip',productId:'dwarf-sword'});
assert.equal(departAdventure(geared,now,'forest',.5).adventure.reward,trip.adventure.reward+5);
const oldPrice=PRODUCTS.find(p=>p.id==='elf-potion').price;PRODUCTS.find(p=>p.id==='elf-potion').price=7;
assert.equal(trade({...initial,coins:10},{type:'buy',shop:'elf',productId:'elf-potion'}).coins,3);PRODUCTS.find(p=>p.id==='elf-potion').price=oldPrice;
assert.equal(BUYBACK.find(b=>b.shop==='dwarf'&&b.material==='moon-stone').price,12);
const closet=trade(initial,{type:'buy',shop:'fairy',productId:'closet'});assert.ok(closet.purchases.includes('closet'));
const potion=PRODUCTS.find(p=>p.id==='elf-potion');potion.enabled=false;assert.throws(()=>trade({...initial,coins:100},{type:'buy',shop:'elf',productId:potion.id}));potion.enabled=true;
console.log('Shops: settings-driven pricing, equipment effects, material return, sales, insufficient balances, item use and duplicate request protection passed.');
